### PR TITLE
adding valgrind to tests and leaks fixes

### PR DESCRIPTION
**Pull request by alexjch**
* Adding a make rule for checking unit tests for memory leaks.
* Properly cleaning memory allocations in tests.
* Fixes to leaks in code.
* Dropping travis CI configuration
* Updating GitHub actions to run new valgrind checks rule.

### CODE REVIEW

**Comment by phmccarty** [comment]
The binary `tests/check_valgrind` is committed. You will want to update the `.gitignore` instead to list the new test binary.

**Comment by phmccarty** [comment]
Do you need to add `tests/tests.supp` to `EXTRA_DIST` as the documentation for the m4 file suggests?

**Comment by alexjch** [comment]
> The binary `tests/check_valgrind` is committed. You will want to update the `.gitignore` instead to list the new test binary.

yeah that sneaked in the code by mistake.

**Comment by alexjch** [comment]
> Do you need to add `tests/tests.supp` to `EXTRA_DIST` as the documentation for the m4 file suggests?

Working on it.

**Comment by phmccarty** [comment]
> > The binary `tests/check_valgrind` is committed. You will want to update the `.gitignore` instead to list the new test binary.
> 
> yeah that sneaked in the code by mistake.

Thanks for removing the binary. Can you update the `.gitignore` too? Otherwise, changes look good to me.

**Comment by alexjch** [comment]
@phmccarty I did not update `.gitignore` because `tests/check_valgrind` is an artifact left during the addition of valgrind to tests (I deleted `tests/check_valgrind.c`, but missed the compiled file)

**Pull request merged**
